### ISSUE TITLE
公告：Google plus将于2019年4月2日停止服务

### ISSUE THREAD

**Issue by the0demiurge** [the0demiurge/ShadowSocksShare#50]
如题，由于当前唯一能爬到好用的帐号就是从Google plus群组里爬到的，请大家多多分享可以用来爬ss帐号的网站：）

请先测试一下确实网站提供的帐号好用再回复：）

**Comment by ga319453** [comment]
google+ 4/2关闭  请加入新群  telegram新创的(https://t.me/terryVPN)
20190328台湾人自架台湾跟香港节点,Google国家级骨干网,本次分享共10gb，不限速，不限使用設備，本ssr使用gcp搭建，節點位置在美國，機房位於臺灣。多重防護保障安全。有需要出差来大陆或是在大陆想要看看世界的速度来找我了，24小时客服在缐及专业远程处理，不会操作的都有视频教学,超级高速高达1000Mbps，专业服务，包您满意。
更多梯子方式及優惠請聯係我WeChat（joyjoy52019），qq（2669437430） telegram新创的(https://t.me/terryVPN) 或者直接messenger我，針對MacOS與iOS用戶提供美區賬號和免費軟件。
節點優勢：
1，後臺不限速，讓您仿似身處國外！
2，後臺不限量，相同的費用用到爽！
3，支持所有系統(Windows,Android,iOS,MacOS,ChromeOS)，一架梯子多機共享！
4，vps來自世界級公司(Google;Amazon;Microsoft)，為您的使用保駕護航！
p.s.最近广州一代电缆光纤线路听说断了,所以补救线路要绕很多站,建议用自己的联通或移动网络测试节点
ssr://MzQuODAuMjIuMjM1OjMzOTk6YXV0aF9hZXMxMjhfbWQ1OmFlcy0xMjgtY3RyOnBsYWluOk1qQXhPVEF6TURSMFpYTjBabTl5WjI5dloyeGwvP29iZnNwYXJhbT0mcmVtYXJrcz02Sy1WNTVTbzViaVE1WS0zTVRCSFF1UzRqZW1aa09tQW4tVzlrLVdrcWVXSXNPYWNuLWFidE9Xa211UzhtT2FEb09pQmxPZXp1LVctcnVTX29XZGhNekU1TkRVeiZncm91cD02Sy1WNTVTbzViaVE1WS0zTVRCSFF1UzRqZW1aa09tQW4tVzlrLVdrcWVXSXNPYWNuLWFidE9Xa211UzhtT2FEb09pQmxPZXp1LVctcnVTX29XZGhNekU1TkRVeg

**Comment by Steve-ShadowsocksR** [comment]
小飞机公益/付费SSR-TG群:https://t.me/FreeSSRfenxiang，内有公益节点和超便宜的付费节点,有需要的小伙伴快来进群哦！

**Comment by Steve-ShadowsocksR** [comment]
小飞机公益/付费SSR-TG群:https://t.me/FreeSSRfenxiang ，内有公益节点和超便宜的付费节点,有需要的小伙伴快来进群哦！

**Comment by hoodiearon** [comment]
G+ rip

**Comment by lisztomania-Zero** [comment]
https://free-ss.site 这个还可以哦！

**Comment by HJ404** [comment]
https://free-ss.site 这个我觉得挺慢的

**Comment by lisztomania-Zero** [comment]
> https://free-ss.site这个我觉得挺慢的

它是实时刷新的，有什么办法可以爬取不？

**Comment by ronghuaxueleng** [comment]
https://akgs.tk/tool/recV3?uri=/tool/free_ssr
可以试试这个

**Comment by lisztomania-Zero** [comment]
https://akgs.tk/tool/recV3?uri=/tool/free_ssr这个访问不了啊

**Comment by ronghuaxueleng** [comment]
https://tays.ml/tool/free_ssr

**Comment by qiaomenzhuang** [comment]
www.xlmb.tk 敲門磚自建機場 註冊送50G 無時間限制，無限擼

**Comment by CoderXingZhang** [comment]
> https://free-ss.site 这个我觉得挺慢的

有没有快点的啊，，

**Comment by cosren** [comment]
https://fanqiang.network/79029.html 请爬

**Comment by the0demiurge** [comment]
我这里显示error 522 connection timeout，连不上这个网站，你能正常连接吗？

此外，我以前写过这个网站的爬虫，爬虫也没有爬到
