### ISSUE TITLE
不成熟的小建议：可以爬telegram里获取ssr地址。

### ISSUE THREAD

**Issue by kpwd** [the0demiurge/ShadowSocksShare#51]
我有一个朋友做过这个，利用bot在群里接收消息，正则过滤获取ssr，或者订阅一些频道获取ssr，不过他已经隐退了

**Comment by the0demiurge** [comment]
倒是可以考虑，不过近期是不会有时间做这个了

**Comment by the0demiurge** [comment]
发现了一个很简单的爬telegram群的方法，已添加两个telegram源
