### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by lzbzzz** [the0demiurge/ShadowSocksShare#69]
019-07-08 21:33:33 ERROR    daemon.py:155 not running
IPv6 support
2019-07-08 21:33:33 INFO     util.py:85 loading libcrypto from libcrypto.so.1.1
started
Testing Connection...
local_port is 1080; if any exceptions orrured, please install jq
connection information:
curl: (52) Empty reply from server

**Comment by lzbzzz** [comment]
日志报错：
ERROR    tcprelay.py:1041 remote error, when connect to clients2.google.com:443

**Comment by the0demiurge** [comment]
换个帐号试试可能就连上了
