### ISSUE TITLE
哪里有vpn账号购买？一个月30左右那种？

### ISSUE THREAD

**Issue by henbucuoshanghai** [the0demiurge/ShadowSocksShare#70]
ss上网，求助哪里购买vpn账号

**Comment by wevsmy** [comment]
有两块钱一个月的需要嘛？🤑

**Comment by henbucuoshanghai** [comment]
确定能用吗 ？稳定？流畅？   vx13052065916

**Comment by wevsmy** [comment]
https://richcloud.xyz/aff.php?aff=1520  这里

**Comment by henbucuoshanghai** [comment]
是吗 确定可以使用吗？

**Comment by henbucuoshanghai** [comment]
购买以后是vpn账号吗？ubuntu不支持？

**Comment by wevsmy** [comment]
2块钱150G流量，是v2ray节点，会使用v2ray就是全终端通用，v2ray的使用方法👉[https://www.v2ray.com/awesome/tools.html](url)  我用了有大半年了吧，还算可以

**Comment by henbucuoshanghai** [comment]
大佬https://www.v2ray.com/awesome/tools.html打不开，搜一下ubuntu或win配置v2ray就可以吗？比如：http://www.357global.com/archives/linuxv2ray.html

**Comment by henbucuoshanghai** [comment]
150g不天天看视频的话，足够了吧  搜个资料什么的

**Comment by ga319453** [comment]
可以聯繫我wechat ga319453 非常穩定且高速

**Comment by wevsmy** [comment]
> 大佬[https://www.v2ray.com/awesome/tools.html打不开，搜一下ubuntu或win配置v2ray就可以吗？比如：http://www.357global.com/archives/linuxv2ray.html](https://www.v2ray.com/awesome/tools.html%E6%89%93%E4%B8%8D%E5%BC%80%EF%BC%8C%E6%90%9C%E4%B8%80%E4%B8%8Bubuntu%E6%88%96win%E9%85%8D%E7%BD%AEv2ray%E5%B0%B1%E5%8F%AF%E4%BB%A5%E5%90%97%EF%BC%9F%E6%AF%94%E5%A6%82%EF%BC%9Ahttp://www.357global.com/archives/linuxv2ray.html)

这个配置网址要翻墙才可以看的，反正我是看视频啥的，没问题，一个月150都用不完

**Comment by ga319453** [comment]
Hi:
    V2ray速度不會快歐,你可以試試看我的ssr,
Ubuntu,Centos,windows,mac,ios,androod,我都有軟件跟教程，可以加我微信ga319453,微信上不要說vp嗯跟翻x,備註下是github就行,我是台灣人有自己台灣的機房，非谷歌雲，騰訊雲，搬瓦公這種不穩定的，可以先給你試用，一個月30左右沒錯，保證讓你快到飛起來

Sincerely,
Terry Chang

wilson_wu <notifications@github.com> 於 2019年7月19日 週五 18:07 寫道：

**Comment by henbucuoshanghai** [comment]
这个配置网址要翻墙才可以看的   那没翻墙呢，看不到配置，翻不了墙。。。

**Comment by anye1998** [comment]
我有，需要吗？可以白嫖几个月，我用着还是挺稳的，各种价位都有。不过只有SSR节点。确认的话可以@我，然后我加你vx

**Comment by vkuajing** [comment]
30 块钱的选择还是很多的。
SS上网的话 JustmySocks 啊， 教程及优惠码： https://vkuajing.net/jms
如果用软件 NordVPN, Vyrpvpn,IvacyVPN ,都符合你 30以内的标准
可以看看这个VPN推荐 https://vkuajing.net/paid-vpn-list/

**Comment by henbucuoshanghai** [comment]
回复的很好，我电脑打不开二个网页。。。  win系统下载一个ss，输入账号密码？

**Comment by vkuajing** [comment]
额，都是被墙的，我给你不墙的链接 ，你自己摸索下
只要SS的话只看JMS就够了

这里下载ShadowSocks软件 https://github.com/shadowsocks
JMS不墙官网镜像 https://vpsland.xyz/go/jms/
5.2%折扣优惠码：JMS9272283

**Comment by yujinpan** [comment]
[蓝鲸 VPN](https://whaleblue.io/zh-hant/) 还可以，台湾的服务商，半年套餐每个月 15 左右，不知道你能不能访问，如果不能可以先用一下蓝灯。

> 推广码免费用一个月：https://jetstream.surf/WHMCS/aff.php?aff=627

**Comment by vpnnice** [comment]
之前玩得是谷歌自建的，现在用的付费的，可以再这网站找到相关信息。[付费VPN](https://www.vpnnice.com/)

**Comment by inwikipedia** [comment]
http://mrw.so/6sLAc5  3个月人民币5.9 每月100G流量 我见过几万个平台上最便宜实惠的唯一的一个!!

**Comment by yytqq** [comment]
https://winlup222.wixsite.com/ss1usd
这是我用wix搭建的小网站，主机搭建的ss,供个人和朋友使用，1000G/每月，有需要的可以一起平摊主机费，每月几块钱

**Comment by yytqq** [comment]
https://winlup222.wixsite.com/ss1usd

**Comment by c6d** [comment]
[here](https://git.io/fjYiA)

**Comment by Leexzyy** [comment]
我用的是自建的 而且可以创建多人账号 需要的话加我 qq 3145694301 价格好商量 反正一起用 一个人流量用不完

**Comment by freesuck** [comment]
本人已由翻墙党官方认证 ，请放心注册使用，注册免费SSR和VPN翻墙，如需VIP服务请充值

https://www.ljvpn.xyz/auth/register?code=duca

注册可用免费稳定不过期节点无需每天来找, 翻墙+免流+原生+独享+中转+私人独享与工作室定制 最低8毛享VIP全站节点 体验合适再加购 支持VPN+SSR 稳定不断流，油管奈飞秒开，游戏流畅稳定。建议使用或收藏以上网址备用，咨询翻墙党发站内信可私聊
不翻也能访问，注册免费翻墙，高端体验翻墙8毛起~移动联通电信有混淆就免流。已稳定运行三年，先试用再决定。包月8元，无限流量。包年53元，无限流量。全站8折优惠，最低4元200G包月  无限流量包年53元 月均4.5/无限。高性价比  国庆春节都稳 新年快乐，出门戴口罩，建议使用或收藏以上网址备用
节点含原生香港台湾新加坡日本美国韩国俄罗斯IP 超高速游戏油管Netflix价格划算
开放1元体验全站VIP，方便大伙感受一分钱一分货的三网超速超稳体验和全国免流功能
套餐折前5元起最高无限+不限时原生IP独享带宽吊打全网共享微软azure欢迎货比三家
本站所含免流功能，如联通定向APP免流，即可用本站VIP全部高速点蹭无限全国流量
应免流用户需求,我在1月13日做全网最全免流教程+免流热点教程发布在[翻墙安全]版块
针对翻墙免流双重需求，以上网站全部VIP节点均在翻墙基础上附加免流功能,欢迎体验
举个例子套餐定向微信APP免流量，用本站任意一个免流的点连上网后不论设备干啥
只要是联网跑流量都会让运营商以为你是用微信产生的流量所以免流不算套餐内流量微信
有追求体验或免流意向建议1块买VIP体验全站节点，像我喜欢免流在外靠这个哈哈哈
坚决保障用户权益，官网附带免流混淆教程参数，感觉好用或免流成功欢迎再加购套餐
谢谢你耐心看我这些文字，感觉合适欢迎你多支持，还有，过年啦，祝咱们新年666

**Comment by freesuck** [comment]
本人已由翻墙党官方认证 ，请放心注册使用，注册免费SSR和VPN翻墙，如需VIP服务请充值

https://sss.888yun.org/auth/register?code=B1PN

注册可用免费稳定不过期节点无需每天来找, 翻墙+免流+原生+独享+中转+私人独享与工作室定制 最低8毛享VIP全站节点 体验合适再加购 支持VPN+SSR 稳定不断流，油管奈飞秒开，游戏流畅稳定。建议使用或收藏以上网址备用，咨询翻墙党发站内信可私聊
不翻也能访问，注册免费翻墙，高端体验翻墙8毛起~移动联通电信有混淆就免流。已稳定运行三年，先试用再决定。包月9元，无限流量。包年59元，无限流量。全站8折优惠，最低4元200G包月  无限流量包年59元 月均4.5/无限。高性价比  国庆春节都稳 新年快乐，出门戴口罩，建议使用或收藏以上网址备用
节点含原生香港台湾新加坡日本美国韩国俄罗斯IP 超高速游戏油管Netflix价格划算
开放1元体验全站VIP，方便大伙感受一分钱一分货的三网超速超稳体验和全国免流功能
套餐折前5元起最高无限+不限时原生IP独享带宽吊打全网共享微软azure欢迎货比三家
本站所含免流功能，如联通定向APP免流，即可用本站VIP全部高速点蹭无限全国流量
应免流用户需求,我在1月13日做全网最全免流教程+免流热点教程发布在[翻墙安全]版块
针对翻墙免流双重需求，以上网站全部VIP节点均在翻墙基础上附加免流功能,欢迎体验
举个例子套餐定向微信APP免流量，用本站任意一个免流的点连上网后不论设备干啥
只要是联网跑流量都会让运营商以为你是用微信产生的流量所以免流不算套餐内流量微信
有追求体验或免流意向建议1块买VIP体验全站节点，像我喜欢免流在外靠这个哈哈哈
坚决保障用户权益，官网附带免流混淆教程参数，感觉好用或免流成功欢迎再加购套餐
谢谢你耐心看我这些文字，感觉合适欢迎你多支持，还有，过年啦，祝咱们新年666

**Comment by freesuck** [comment]
本人已由翻墙党官方认证 ，请放心注册使用，注册免费SSR和VPN翻墙，如需VIP服务请充值

https://www.oness.me/auth/register?code=dPIp

注册可用免费稳定不过期节点无需每天来找, 翻墙+免流+原生+独享+中转+私人独享与工作室定制 最低8毛享VIP全站节点 体验合适再加购 支持VPN+SSR 稳定不断流，油管奈飞秒开，游戏流畅稳定。建议使用或收藏以上网址备用，咨询翻墙党发站内信可私聊
不翻也能访问，注册免费翻墙，高端体验翻墙8毛起~移动联通电信有混淆就免流。已稳定运行三年，先试用再决定。包月8元，无限流量。包年53元，无限流量。全站8折优惠，最低4元200G包月  无限流量包年53元 月均4.5/无限。高性价比  国庆春节都稳 新年快乐，出门戴口罩，建议使用或收藏以上网址备用
节点含原生香港台湾新加坡日本美国韩国俄罗斯IP 超高速游戏油管Netflix价格划算
开放1元体验全站VIP，方便大伙感受一分钱一分货的三网超速超稳体验和全国免流功能
套餐折前5元起最高无限+不限时原生IP独享带宽吊打全网共享微软azure欢迎货比三家
本站所含免流功能，如联通定向APP免流，即可用本站VIP全部高速点蹭无限全国流量
应免流用户需求,我在1月13日做全网最全免流教程+免流热点教程发布在[翻墙安全]版块
针对翻墙免流双重需求，以上网站全部VIP节点均在翻墙基础上附加免流功能,欢迎体验
举个例子套餐定向微信APP免流量，用本站任意一个免流的点连上网后不论设备干啥
只要是联网跑流量都会让运营商以为你是用微信产生的流量所以免流不算套餐内流量微信
有追求体验或免流意向建议1块买VIP体验全站节点，像我喜欢免流在外靠这个哈哈哈
坚决保障用户权益，官网附带免流混淆教程参数，感觉好用或免流成功欢迎再加购套餐
谢谢你耐心看我这些文字，感觉合适欢迎你多支持，还有，过年啦，祝咱们新年666

**Comment by inwikipedia** [comment]
http://suo.im/5W3v7b 3个月人民币5.9 每月100G流量 我见过几万个平台上最便宜实惠的唯一的一个!!

**Comment by freesuck** [comment]
不可能100G还叫便宜啊 
无限流量你懂？













在 2020-04-07 17:31:59，"Donald X. Rhodes" <notifications@github.com> 写道：

http://suo.im/5W3v7b 3个月人民币5.9 每月100G流量 我见过几万个平台上最便宜实惠的唯一的一个!!

**Comment by xyy7260** [comment]
> https://url.cn/5pY7upd 3个月人民币5.9 每月100G流量 我见过几万个平台上最便宜实惠的唯一的一个!!

我这边看到，不止你说的那么便宜把·

**Comment by henbucuoshanghai** [comment]
确定可以？

**Comment by yujinpan** [comment]
我发现 [pandavpn](https://www.pandavpnpro.com/) 做的还可以，比较稳定，[GooglePlay- PandaVPN Pro](https://play.google.com/store/apps/details?id=com.pandavpn.androidproxy&hl=zh) 评论不错，反馈很积极，有兴趣的输入[邀请码](https://www.pancerra.xyz/i/15065596)互相增加一个月的使用时间。
😃

**Comment by AINightCoder** [comment]
> https://richcloud.xyz/aff.php?aff=1520 这里

这个人推荐的不能用, 给的节点没一个好使的, google都打不开, 还退不了款,  后面的人看到了别上当了

**Comment by trackerstill** [comment]
这个挺便宜的，用了3个月，买断制，也不会卡
https://neukssr.club/auth/register?code=FfbK

**Comment by niuniuhenniu** [comment]
> ss上网，求助哪里购买vpn账号

加微信597717087

**Comment by henbucuoshanghai** [comment]
@anye1998   可以加一下微信？13052065916

**Comment by niuniuhenniu** [comment]
没钱就别装逼，耽误老子时间



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: henbucuoshanghai <notifications@github.com&gt;
发送时间: 2020年6月13日 11:18
收件人: the0demiurge/ShadowSocksShare <ShadowSocksShare@noreply.github.com&gt;
抄送: wjw514728 <597717087@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[the0demiurge/ShadowSocksShare] 哪里有vpn账号购买？一个月30左右那种？ (#70)





 
@anye1998   可以加一下微信？13052065916

**Comment by wojiazaiyugang** [comment]
这个还挺好，一直用挺稳定的，就查个文档，看过几次视频也没啥问题
https://jiyou.world/aff.php?aff=9701

**Comment by 18731608391** [comment]
> 有两块钱一个月的需要嘛？🤑

老哥，我需要，你加我还是我加你啊，我vx，18731608391，加我备注一下2元梯子就行

**Comment by henbucuoshanghai** [comment]
我做翻墙的  便宜 实用  linux win系统  各类 手机随便翻墙，vx13052065916
