### ISSUE TITLE
设想

### ISSUE THREAD

**Issue by cms42** [the0demiurge/ShadowSocksShare#71]
可不可以部署在GAE(Google App Engine)上，爬取后直接自动上传到一个特定地点（比如Gittalk或PUSH一个Git Repo），然后本地客户端自动下载
或者GAE套上Cloudflare代理
或者传到一个s3储存库上
等等
@the0demiurge

**Comment by the0demiurge** [comment]
这些都比普通网站方法多需要一个账号，这样复杂性会提高，更容易被制裁，而且也更麻烦
