### ISSUE TITLE
ubuntu使用ss上网

### ISSUE THREAD

**Issue by henbucuoshanghai** [the0demiurge/ShadowSocksShare#78]
以前是设置好manual-    socks host

然后命令 sslocal -s 账号-p 8097 -k "密码" -b 127.0.0.1 -l 1080 
就可以翻墙   

操作很简单
请问这是怎样操作的呢？忘了。。。。
求教

**Comment by itsongsong** [comment]
![image](https://user-images.githubusercontent.com/21120408/64667114-4eda9000-d48b-11e9-8b50-18c07d301037.png)

用这个软件就好了：`qt5`

**Comment by henbucuoshanghai** [comment]
可以给一个使用操作吗？   安装好，输入账号密码端口vpn就可以吗？

**Comment by itsongsong** [comment]
安装这个软件`qt5`后，chrome安装代理插件：`SwitchyOmega`。配置一下就好了代理就好了，网上很多教程的。

**Comment by henbucuoshanghai** [comment]
没用过这种办法    不会。。       qt5下载sh文件安装是吗？sh文件有1g多是吗？

**Comment by itsongsong** [comment]
软件中心就有


![软件中心.png](https://i.loli.net/2019/09/11/jHdRmicL8XPCv4q.png)

**Comment by henbucuoshanghai** [comment]
大佬   qt5安装好了，switchomega安装好  界面是这样的  接下来哪里输入vpn的账号密码呢？不懂
